# Generated by Django 5.1.7 on 2025-03-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="weatherdata",
            old_name="feels_like",
            new_name="avg_temperature",
        ),
        migrations.RenameField(
            model_name="weatherdata",
            old_name="temperature",
            new_name="max_temperature",
        ),
        migrations.RenameField(
            model_name="weatherdata",
            old_name="wind_speed",
            new_name="max_wind_speed",
        ),
        migrations.RemoveField(
            model_name="weatherdata",
            name="timestamp",
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="chance_of_rain",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="chance_of_snow",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="date",
            field=models.DateField(default="2025-01-01"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="min_temperature",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
