# Generated by Django 5.1.7 on 2025-03-11 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0002_rename_feels_like_weatherdata_avg_temperature_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="weatherdata",
            unique_together={("city", "date")},
        ),
    ]
